# Generated by Django 3.2.11 on 2022-01-22 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(unique=True)),
                ('kyc_poi', models.ImageField(unique=True, upload_to='partner_onbarding/')),
                ('kyc_poa', models.ImageField(unique=True, upload_to='partner_onbarding/')),
                ('shop_owner_photo', models.ImageField(upload_to='partner_onbarding/profile_pic')),
                ('shop_photo_with_owner', models.ImageField(upload_to='partner_onbarding/shop_photo_with_owner')),
                ('shop_front_photo', models.ImageField(upload_to='partner_onbarding/shop_front_photo')),
                ('lat_long', models.IntegerField()),
                ('shop_name', models.CharField(max_length=200)),
                ('other_documents', models.FileField(null=True, upload_to='partner_onbarding/other_documents')),
                ('name_of_partners1', models.CharField(max_length=200)),
                ('name_of_partners2', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('similar_address', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=400)),
                ('email_id', models.CharField(max_length=200, unique=True)),
                ('alternate_mo_no', models.IntegerField()),
                ('business_category', models.CharField(max_length=400)),
                ('number_of_merchants', models.IntegerField()),
                ('annual_income', models.IntegerField()),
                ('no_of_employees', models.IntegerField()),
                ('aadhaar_cibil', models.CharField(max_length=300)),
                ('locations_covered', models.IntegerField()),
                ('bank_ifsc', models.CharField(max_length=400)),
                ('bank_account_number', models.IntegerField(unique=True)),
                ('bank_account_name', models.CharField(max_length=400)),
                ('bank_name', models.CharField(max_length=400)),
                ('additional_comments', models.TextField(max_length=500, null=True)),
                ('is_delete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 12, 28, 11, 76398))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approve_reject', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('digital_agreement', models.BooleanField(default=False)),
            ],
        ),
    ]
