# Generated by Django 3.2.11 on 2022-01-22 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_p_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('NEFT', 'NEFT'), ('IMPS', 'IMPS'), ('UPI', 'UPI')], max_length=200)),
                ('payment_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 12, 30, 8, 869787))),
                ('transaction_no', models.CharField(max_length=400)),
                ('account_head', models.CharField(max_length=200)),
                ('ac_holder_name', models.CharField(max_length=200)),
                ('ac_no', models.CharField(max_length=400, unique=True)),
                ('ifsc_code', models.CharField(max_length=200, unique=True)),
                ('bank_name', models.CharField(max_length=400)),
                ('branch_name', models.CharField(max_length=400)),
                ('kyc_proof', models.ImageField(upload_to='Insurance_p_collection/kyc_proof/')),
                ('kyc_type', models.CharField(choices=[('PAN', 'PAN Card'), ('Voter', 'Voter ID'), ('Driving', 'Driving Licence')], max_length=200)),
                ('id_number', models.IntegerField()),
                ('bank_proof', models.ImageField(upload_to='Insurance_p_collection/bank_proof/')),
                ('payment_receipt', models.ImageField(upload_to='Insurance_p_collection/payment_receipt/')),
                ('is_delete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 12, 30, 8, 869787))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
